<a href="https://colab.research.google.com/github/SLCFLAB/Fintech2026-1/blob/main/DL_day4/4_1_gpu_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch basics & Autograd



## CPU, GPU

In [1]:
# Get OS info
!cat /etc/issue.net

Ubuntu 22.04.5 LTS


In [2]:
# Get CPU info
!cat /proc/cpuinfo | grep 'processor\|model name\|cpu cores'

processor	: 0
model name	: Intel(R) Xeon(R) CPU @ 2.00GHz
cpu cores	: 1
processor	: 1
model name	: Intel(R) Xeon(R) CPU @ 2.00GHz
cpu cores	: 1


In [3]:
# Get GPU info
!nvidia-smi

Tue Mar  3 07:58:05 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   63C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Pytorch, Tensor

In [4]:
import torch

In [5]:
torch.__version__

'2.10.0+cu128'

In [6]:
!pip show torch

Name: torch
Version: 2.10.0+cu128
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org
Author: 
Author-email: PyTorch Team <packages@pytorch.org>
License: BSD-3-Clause
Location: /usr/local/lib/python3.12/dist-packages
Requires: cuda-bindings, filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-cufile-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-cusparselt-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvshmem-cu12, nvidia-nvtx-cu12, setuptools, sympy, triton, typing-extensions
Required-by: accelerate, fastai, peft, sentence-transformers, timm, torchaudio, torchdata, torchvision


## 1.1 Tensor Basic

In [7]:
#Tensor의 기초적 선언
#torch.FloatTensor와 같음
# x = torch.Tensor(행, 열)
x = torch.Tensor(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
#Tesnor의 정보 확인
print("Tensor Type : ", type(x))
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size()) # x.shape

Tensor Type :  <class 'torch.Tensor'>
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


## 1.2 Tensor with characteristics

In [9]:
#0으로 채워진 Tensor 선언
x = torch.zeros(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [10]:
x = torch.zeros(2,3, dtype=torch.int32)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 3])


In [11]:
#1로 채워진 Tensor 선언
x = torch.ones(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [12]:
#0, 1 사이의 랜덤 숫자로 채워진 Tensor 선언
x = torch.rand(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0.1248, 0.7529, 0.6021],
        [0.0498, 0.9896, 0.2580]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [13]:
#평균이 0이고 분산이 1을 따르는 정규분포에서 추출된 값으로 채워진 Tensor 선언
x = torch.randn(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[ 0.4584,  0.2814, -0.3560],
        [ 0.1098, -1.9587,  0.4423]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [14]:
#정방행렬과 같은 Tensor 선언
x = torch.eye(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 0., 0.],
        [0., 1., 0.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [15]:
#0부터 2까지 0.5씩 증가하는 Tensor 선언
x = torch.arange(0, 2, step=0.5)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([0.0000, 0.5000, 1.0000, 1.5000])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([4])


In [16]:
#직접 값을 입력하여 선언
x = torch.Tensor([[1,2,3],[1,2,3]])
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [17]:
#32-bit floating point
x = torch.FloatTensor(2,3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1.6100e+01, 0.0000e+00, 8.0024e+00],
        [0.0000e+00, 8.9683e-44, 0.0000e+00]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [18]:
#32-bit integer (signed)
x = torch.IntTensor(2,3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1098852240,          0, 1098953888],
        [         0,         32,          0]], dtype=torch.int32)
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 3])


## 1.3 Tensor and Numpy

In [19]:
import numpy as np

In [20]:
#numpy 형식의 배열
x = np.array([[1,2,3],[1,2,3]])
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


In [21]:
#numpy를 tensor로 변환
x = torch.from_numpy(x) # x = torch.Tensor(x)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1, 2, 3],
        [1, 2, 3]])
Tensor Type :  torch.LongTensor
Tensor Size :  torch.Size([2, 3])


In [22]:
#tensor를 numpy로 변환
x = x.numpy()
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


## 1.4 Tensor Slicing

In [23]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [24]:
#모든 원소 출력
x[:, :]

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [25]:
#2행부터 출력
x[1:, :]

tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [26]:
#2열부터 출력
x[:, 1:]

tensor([[ 2.,  3.,  4.],
        [ 6.,  7.,  8.],
        [10., 11., 12.]])

In [27]:
#2행, 2열부터 3열까지 출력
x[1:, 1:3]

tensor([[ 6.,  7.],
        [10., 11.]])

In [28]:
#1행 출력
x[0, :]

tensor([1., 2., 3., 4.])

In [29]:
#x를 1행씩 잘라서 배열로 저장
x_rows = torch.split(x, split_size_or_sections=1, dim=0)
print(x_rows)

(tensor([[1., 2., 3., 4.]]), tensor([[5., 6., 7., 8.]]), tensor([[ 9., 10., 11., 12.]]))


In [30]:
#x를 2열씩 잘라서 배열로 저장
x_cols = torch.split(x, split_size_or_sections=2, dim=1)
print(x_cols)

(tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]), tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]))


In [31]:
#위와 같은 결과
torch.chunk(x, chunks=2, dim=1)

(tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]),
 tensor([[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]))

## 1.5 Tensor Merging

In [32]:
#x_rows를 행으로 이어 붙이기
torch.cat(x_rows, dim=0)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [33]:
#x_rows를 열로 이어 붙이기
torch.cat(x_rows, dim=1)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [34]:
#x_cols를 쌓아올리기
x_new = torch.stack(x_cols, dim=0)
print(x_new)

tensor([[[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]],

        [[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]])


## 1.6 Tensor Reshaping

In [35]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [36]:
#4행 3열로 바꾸기
x.view(4, 3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [37]:
#2열로 바꾸기
x.view(-1, 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [38]:
x.view(2, 1, -1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

In [39]:
#차원이 1인 값을 축소: (2,6)
x.view(2, 1, -1).squeeze()

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [40]:
#dim=1 자리에 차원을 추가: (2,1,6)
x.view(2, 1, -1).squeeze().unsqueeze(dim=1).size()

torch.Size([2, 1, 6])

## 1.7 Tensor Calculation

In [41]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print("x :", x)
print("y :", y)

x : tensor([[1., 2., 3.],
        [4., 5., 6.]])
y : tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [42]:
# x와 y의 합
z = torch.add(x, y)
print("z :", z)
print("x+y :", x+y)

z : tensor([[2., 3., 4.],
        [6., 7., 8.]])
x+y : tensor([[2., 3., 4.],
        [6., 7., 8.]])


In [43]:
# x의 모든 원소에서 2를 뺌
print(x - 2)

# x의 모든 원소에 2를 곱함
print(2*x)

tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [44]:
#x의 원소와 y의 원소를 각각 곱함
z = torch.mul(x, y)
print("z :", z)
print("x*y :", x*y)

z : tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])
x*y : tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])


In [45]:
#x의 원소를 각각 제곱함
z = torch.pow(x, 2)
print("z :", z)
print("x**2 :", x**2)

z : tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
x**2 : tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [46]:
#x의 원소에 log를 씌움
z = torch.log(x)
print("z :", z)
print("x.log() :", x.log())

z : tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
x.log() : tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])


In [47]:
#x의 원소에 루트를 씌움
z = torch.sqrt(x)
print("z :", z)
print("x.sqrt() :", x.sqrt())

z : tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
x.sqrt() : tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])


In [48]:
#x의 원소에 나머지(mod) 계산
z = x % 2
print(z)

tensor([[1., 0., 1.],
        [0., 1., 0.]])


In [49]:
#x에 절댓값
z = torch.abs(x)
print("z :", z)
print("x.abs() :", x.abs())

z : tensor([[1., 2., 3.],
        [4., 5., 6.]])
x.abs() : tensor([[1., 2., 3.],
        [4., 5., 6.]])


## 1.9 Tensor Statistic

In [50]:
x = torch.Tensor([[-1,2,-3],[4,-5,6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [51]:
print("x의 합 :", x.sum())
print("x의 최대값 :", x.max())
print("x의 최소값 :", x.min())
print("x의 분산 :", x.var())

x의 합 : tensor(3.)
x의 최대값 : tensor(6.)
x의 최소값 : tensor(-5.)
x의 분산 : tensor(17.9000)


In [52]:
# Scalar Tensor
x.sum().size()

torch.Size([])

In [53]:
# item의 활용
print("x의 합 :", x.sum().item())
print("x의 최대값 :", x.max().item())
print("x의 최소값 :", x.min().item())
print("x의 분산 :", x.var().item())

x의 합 : 3.0
x의 최대값 : 6.0
x의 최소값 : -5.0
x의 분산 : 17.899999618530273


In [54]:
#행(dim=0)을 기준으로 열의 최댓값을 출력
value, index = x.max(dim=0)
value, index

(tensor([4., 2., 6.]), tensor([1, 0, 1]))

In [55]:
#열(dim=1)을 기준으로 행의 최댓값을 출력
value, index = x.max(dim=1)
value, index

# torch.max(x, dim=1)과 같은 결과
# 이는 추후에 계속 등장하므로 매우 중요!

(tensor([2., 6.]), tensor([1, 2]))

In [56]:
#열(dim=1)을 기준으로 각 행을 정렬
value, index = x.sort(dim=1)
value

tensor([[-3., -1.,  2.],
        [-5.,  4.,  6.]])

## 1.11 Tensor for GPU

In [57]:
# cuda 확인
print("현재 Cuda 사용 가능한 Device 개수 :", torch.cuda.device_count())
print("현재 Cuda 사용 가능 여부 :", torch.cuda.is_available())
print("현재 사용 중인 Cuda Device :", torch.cuda.current_device())
print("현재 Cuda Device 이름 :", torch.cuda.get_device_name(0))
print("현재 Cuda Device의 사용 가능한 메모리 :", torch.cuda.max_memory_allocated(device=0), "bytes")
print("현재 Cuda Device의 사용 중인 메모리 :", torch.cuda.memory_allocated(device=0), "bytes")

현재 Cuda 사용 가능한 Device 개수 : 1
현재 Cuda 사용 가능 여부 : True
현재 사용 중인 Cuda Device : 0
현재 Cuda Device 이름 : Tesla T4
현재 Cuda Device의 사용 가능한 메모리 : 0 bytes
현재 Cuda Device의 사용 중인 메모리 : 0 bytes


In [58]:
# cuda 세팅
torch.cuda.set_device(0)

In [59]:
x = torch.Tensor([[1,2,3],[1,2,3]])
print(x)

tensor([[1., 2., 3.],
        [1., 2., 3.]])


In [60]:
#cpu를 gpu로 전환
gpu_x = x.cuda()
print(gpu_x)
print("Tensor Type : ", gpu_x.type())
print("Tensor Size : ", gpu_x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]], device='cuda:0')
Tensor Type :  torch.cuda.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [61]:
#cpu를 gpu로 전환 2
device = torch.device("cuda")
gpu_x = x.to(device)
print(gpu_x)
print("Tensor Type : ", gpu_x.type())
print("Tensor Size : ", gpu_x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]], device='cuda:0')
Tensor Type :  torch.cuda.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [62]:
#gpu를 cpu로 전환
x = gpu_x.cpu()
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [63]:
#gpu를 cpu로 전환 2
device = torch.device("cpu")
x = gpu_x.to(device)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [64]:
# gpu tensor와 cpu tensor의 연산
gpu_x + x

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

## 1.12 Tensor Calculation as Matrix (참고)

In [65]:
x = torch.Tensor([[1,1],[2,2]])
y = torch.Tensor([[1,2],[3,4]])
print("x :", x)
print("y :", y)

x : tensor([[1., 1.],
        [2., 2.]])
y : tensor([[1., 2.],
        [3., 4.]])


In [66]:
#x와 y의 행렬곱
torch.mm(x, y)

tensor([[ 4.,  6.],
        [ 8., 12.]])

In [67]:
#x와 z의 행렬벡터곱
z = torch.Tensor([1, 2])
torch.mv(x, z)

tensor([3., 6.])

In [68]:
#z와 z의 내적
torch.dot(z, z)

tensor(5.)

In [69]:
#x의 전치(transpose)
x.t()

tensor([[1., 2.],
        [1., 2.]])

In [70]:
# y의 역행렬(inverse)
y.inverse()

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

In [71]:
# 텐서의 배치 행렬곱
x1 = torch.FloatTensor(3,3,2)
x2 = torch.FloatTensor(3,2,3)

torch.bmm(x1,x2).size()

torch.Size([3, 3, 3])

In [72]:
x1

tensor([[[-1.3232e-25,  4.3757e-41],
         [ 1.6266e+01,  0.0000e+00],
         [ 1.6113e+01,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 9.0818e+04,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]]])

In [73]:
# 텐서의 전치
x1.transpose(0,2)

tensor([[[-1.3232e-25,  0.0000e+00,  0.0000e+00],
         [ 1.6266e+01,  0.0000e+00,  0.0000e+00],
         [ 1.6113e+01,  9.0818e+04,  0.0000e+00]],

        [[ 4.3757e-41,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [76]:
eigenvalue, eigenvector = torch.linalg.eig(x)
print("eigenvalue :", eigenvalue)
print("eigenvector :", eigenvector)

eigenvalue : tensor([1.1921e-07+0.j, 3.0000e+00+0.j])
eigenvector : tensor([[-0.7071+0.j, -0.4472+0.j],
        [ 0.7071+0.j, -0.8944+0.j]])


In [77]:
#행렬의 QR factorization
Q,R = torch.qr(x)
print("Q :", Q)
print("R :", R)

Q : tensor([[-0.4472, -0.8944],
        [-0.8944,  0.4472]])
R : tensor([[-2.2361e+00, -2.2361e+00],
        [ 0.0000e+00,  1.1921e-07]])


In [78]:
#행렬의 SVD factorization
S,V,D = torch.svd(x)
print("S :", S)
print("V :", V)
print("D :", D)

S : tensor([[-0.4472, -0.8944],
        [-0.8944,  0.4472]])
V : tensor([3.1623e+00, 5.2283e-08])
D : tensor([[-0.7071, -0.7071],
        [-0.7071,  0.7071]])


# 2. Autograd

In [79]:
import torch

## 2.1 Autograd

In [80]:
x = torch.ones(1)
x.requires_grad

False

In [81]:
y = torch.ones(1)
y.requires_grad

False

In [82]:
z = x + y

In [83]:
z.requires_grad

False

In [84]:
x.requires_grad=True
x.requires_grad

True

In [85]:
z = x + y

In [86]:
z.requires_grad

True

## 2.2 Backward

In [87]:
y = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)
y

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [88]:
z = 2*y + 1
z

tensor([[3., 5.],
        [7., 9.]], grad_fn=<AddBackward0>)

In [89]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)

print("")

print("y.grad :", y.grad)
print("z.grad :", z.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)

y.requires_grad : True
z.requires_grad : True

y.grad : None
z.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x79f94e2ef220>


/tmp/ipykernel_493/3957125995.py:7: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:492.)
  print("z.grad :", z.grad)


In [90]:
# grad can be implicitly created only for scalar outputs
z.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [91]:
out = z.sum()
out

tensor(24., grad_fn=<SumBackward0>)

In [92]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)
print("out.requires_grad :", out.requires_grad)

print("")

print("y.grad :", y.grad)
print("z.grad :", z.grad)
print("out.grad :", out.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)
print("out.grad_fn :", out.grad_fn)

y.requires_grad : True
z.requires_grad : True
out.requires_grad : True

y.grad : None
z.grad : None
out.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x79f94e2ef610>
out.grad_fn : <SumBackward0 object at 0x79f94e2ef610>


/tmp/ipykernel_493/925780261.py:8: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:492.)
  print("z.grad :", z.grad)
/tmp/ipykernel_493/925780261.py:9: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytor

In [93]:
out.backward()

In [94]:
print("y.grad :", y.grad)
print("z.grad :", z.grad)
print("out.grad :", out.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)
print("out.grad_fn :", out.grad_fn)

y.grad : tensor([[2., 2.],
        [2., 2.]])
z.grad : None
out.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x79f94ea37d00>
out.grad_fn : <SumBackward0 object at 0x79f94ea37d00>


/tmp/ipykernel_493/2641464651.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:492.)
  print("z.grad :", z.grad)
/tmp/ipykernel_493/2641464651.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pyt

## 2.3 Detach from Autograd & .detach() vs .data

In [95]:
# Graph 위에 있는 변수는 바로 numpy로 변환할 수 없음.
z.numpy()

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [97]:
# 따라서 .detach와 .data 중 하나를 사용해야함.
z.detach().numpy()

array([[3., 5.],
       [7., 9.]], dtype=float32)

In [98]:
# 따라서 .detach와 .data 중 하나를 사용해야함.
z.data.numpy()

array([[3., 5.],
       [7., 9.]], dtype=float32)